apiVersion: v1
kind: Service
metadata:
  namespace: wsdm-akka-1
  name: mongodb
spec:
  ports:
    - port: 27017
  selector:
    app: mongodb
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: wsdm-akka-1
  name: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongo
          image: mongo:latest
          env:
            - name: MONGO_INITDB_DATABASE
              value: "wsdm-akka"
          ports:
            - containerPort: 27017
              name: mongodb